# Generated by Django 2.2.5 on 2021-04-16 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210416_0949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='product',
        ),
        migrations.AddField(
            model_name='favorite',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Customer'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='favproducts',
            field=models.ManyToManyField(to='store.Product'),
        ),
    ]
