# Generated by Django 2.2.5 on 2021-04-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20210416_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='favproducts',
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Favorite')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.Product')),
            ],
        ),
    ]
