# Generated by Django 2.2.5 on 2021-04-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20210416_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingaddress',
            name='cod',
            field=models.BooleanField(default=False),
        ),
    ]
